### ISSUE TITLE
"Could you please provide guidance on how to connect the screen and CAN?"

### ISSUE THREAD

**Issue by mk11996** [themelisx/ESP32CarODB#5]

**Comment by themelisx** [comment]
@mk11996 Right now there is no support for CanBus

**Comment by mk11996** [comment]
Can you tell me how to connect the screen?

**Comment by themelisx** [comment]
@mk11996 You can see the definition inside the code about the pin that used.
Also there is a photo at the readme that shows the cable (colors) that are connected to the ESP32
https://raw.githubusercontent.com/themelisx/ESP32CarODB/main/photos/IMG_20231229_184143.jpg
